import Head from 'next/head'
import Image from 'next/image'

// Link component help us to create full navigation system (Routing system)
import Link from "next/link"

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the eLearning Platform
        </h1>

        <div className={styles.grid}>
          <Link href="/learn/learnNext">
          <div className={styles.card}>
            <h2>Learn Next.js &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>
          </Link>

          <Link legacyBehavior href="/learn/learnReact">
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn React.js &rarr;</h2>
            <p>Learn about React.js in an interactive course with quizzes!</p>
          </a>
          </Link>

          <a href="learn/learnVue"
            className={styles.card}
          >
            <h2>Learn Vue.js &rarr;</h2>
            <p>Learn about Vue.js in an interactive course with quizzes!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
